=== Anisha-Karmacharya/Vehicle-Catalog/XML, CSS, XSD/Catalog_18030846.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"> 
<!-- Anisha Karmacharya -->
<!-- 04/15/2020 -->
<!--Root Element-->
	<xs:element name="Vehicle" type="VehicleType">
		<xs:complexType name="VehicleType">
			<xs:sequence><!--to declare the child element in order-->
			  <xs:element type="headerType" name="header"/>
			  <xs:element type="ShopType" name="Shop"/>
			  <xs:element type="xs:string" name="Intro"/>
			  <xs:element type="CarsType" name="Cars"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ShopType">
		<xs:sequence>
		  <xs:element type="xs:string" name="shopLocation"/>
		  <xs:element type="xs:string" name="shopNumber"/>
		  <xs:element type="xs:string" name="shopWebsite"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="shopID"/>
	</xs:complexType>
	<xs:complexType name="headerType">
		<xs:sequence>
		  <xs:element type="xs:string" name="logo"/>
		  <xs:element type="xs:string" name="shopName"/>
		</xs:sequence>
	</xs:complexType>
    <xs:complexType name="CarsType">
		<xs:sequence>
		  <xs:element type="CarType" name="Car" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
    </xs:complexType>
    <xs:complexType name="CarType">
		<xs:sequence>
		  <xs:element type="modelNameType" name="modelName"/>
		  <xs:element type="xs:string" name="accord" minOccurs="0"/>
		  <xs:element type="xs:string" name="audi" minOccurs="0"/>
		  <xs:element type="xs:string" name="civic" minOccurs="0"/>
		  <xs:element type="xs:string" name="accent" minOccurs="0"/>
		  <xs:element type="xs:string" name="bolt" minOccurs="0"/>
		  <xs:element type="carDescriptionType" name="carDescription"/>
		  <xs:element type="specificationType" name="specification"/>
		  <xs:element type="xs:string" name="accord1" minOccurs="0"/>
		  <xs:element type="xs:string" name="audi1" minOccurs="0"/>
		  <xs:element type="xs:string" name="civic1" minOccurs="0"/>
		  <xs:element type="xs:string" name="accent1" minOccurs="0"/>
		  <xs:element type="xs:string" name="bolt1" minOccurs="0"/>
		</xs:sequence>
    </xs:complexType>
    <xs:complexType name="modelNameType">
		<xs:simpleContent>
		  <xs:extension base="xs:string">
			<xs:attribute type="xs:string" name="modelNumber" use="optional"/>
		  </xs:extension>
		</xs:simpleContent>
	</xs:complexType>
    <xs:complexType name="carDescriptionType">
		<xs:sequence>
		  <xs:element type="xs:string" name="h1"/>
		  <xs:element type="xs:string" name="p"/>
		</xs:sequence>
    </xs:complexType>
	<xs:complexType name="specificationType">
		<xs:sequence>
		  <xs:element type="xs:string" name="specs"/>
		  <xs:element type="xs:string" name="carBrand"/>
		  <xs:element type="xs:string" name="carType"/>
		  <xs:element type="xs:string" name="EPAClassification"/>
		  <xs:element type="xs:string" name="seatCapacity"/>
		  <xs:element type="xs:string" name="carColor"/>
		  <xs:element type="xs:string" name="dimension"/>
		  <xs:element type="xs:string" name="driveType"/>
		  <xs:element type="xs:string" name="engineCapacity" minOccurs="0"/>
		  <xs:element type="xs:string" name="engineConfiguration"/>
		  <xs:element type="xs:string" name="fuelSystem"/>
		  <xs:element type="xs:string" name="fuelCapacity" minOccurs="0"/>
		  <xs:element type="xs:string" name="gasMileage" minOccurs="0"/>
		  <xs:element type="xs:string" name="fuelType" minOccurs="0"/>
		  <xs:element type="xs:string" name="transmission"/>
		  <xs:element type="xs:string" name="cargoAreaDimensions"/>
		  <xs:element type="xs:string" name="steering"/>
		  <xs:element type="xs:string" name="frontSuspension"/>
		  <xs:element type="xs:string" name="rearSuspension"/>
		  <xs:element type="xs:string" name="brakeType"/>
		  <xs:element type="xs:string" name="antiLockBraking"/>
		  <xs:element type="xs:string" name="WheelSize"/>
		  <xs:element type="xs:string" name="WheelMaterial"/>
		  <xs:element type="xs:string" name="tireSize"/>
		  <xs:element type="xs:string" name="carPrice"/>
		  <xs:element type="ReviewType" name="Review"/>
		  <xs:element type="xs:string" name="quantity"/>
		</xs:sequence>
    </xs:complexType>
    <xs:complexType name="ReviewType">
		<xs:simpleContent>
		  <xs:extension base="xs:string">
			<xs:attribute type="xs:float" name="Comfort" use="optional"/>
			<xs:attribute type="xs:float" name="ExteriorStyling" use="optional"/>
			<xs:attribute type="xs:float" name="InteriorDesign" use="optional"/>
			<xs:attribute type="xs:float" name="Performance" use="optional"/>
			<xs:attribute type="xs:float" name="Reliability" use="optional"/>
			<xs:attribute type="xs:float" name="ValueForTheMoney" use="optional"/>
		  </xs:extension>
		</xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== Anisha-Karmacharya/Vehicle-Catalog/XML, CSS, XSD/catalog_18030846.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="catalog_18030846.css"?> 
<!-- Anisha Karmacharya -->
<!-- 03/29/2020 -->
<Vehicle xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 		xsi:noNamespaceSchemaLocation="catalog_18030846.xsd">
	<Shop shopID="SH890-041-02">	
		<shopLocation>Address: Putalisadak</shopLocation>
		<shopNumber>Phone Number: 014531115</shopNumber>
		<shopWebsite>Website: www.autocompany.com.np</shopWebsite>
	</Shop>
	<header>
		<logo></logo>
		<shopName>Motor Station</shopName>
	</header>
	<Intro>Drive your will</Intro>
	<Cars>		
		<Car>
			<modelName modelNumber="G-12345-6788"> Accord LX 1.5T CVT</modelName>
			<accord/>
				<carDescription>
					<h1> Description </h1>
					<p>
						The Accord is Honda’s five-seat mid-size family sedan. Now in its 10th generation, 
						the front-wheel-drive Accord comes with a standard 192-horsepower, turbocharged 
						1.5-liter four-cylinder engine or an available 252-hp, turbocharged 2.0-liter four-cylinder.
						A six-speed manual transmission is available for both engines. The 1.5-liter engine can also
						work with a continuously variable automatic transmission while the 2.0-liter engine can pair
						with a 10-speed automatic. There’s also an efficient Accord Hybrid with a two-motor hybrid 
						powertrain that incorporates a 2.0-liter four-cylinder and gets an EPA-estimated 48 mpg combined. 
					</p>
				</carDescription>
				<specification>
				<specs>Specifications</specs>
				<carBrand>Make: Honda</carBrand>
				<carType>Type: Sedan</carType>
				<EPAClassification>EPA Classification: Mid-size Car</EPAClassification>
				<seatCapacity>Seat Capacity: 5</seatCapacity>
				<carColor>Color: Grey</carColor>
				<dimension>Dimension (L x W x H): 4,890 x 1,850 x 1,465) mm</dimension>
				<driveType>Drive Type: Front Wheel Drive</driveType>
				<engineCapacity> Engine Capacity: 1,997 cc </engineCapacity>
				<engineConfiguration>Engine Type: In-Line 4-Cylinder</engineConfiguration>
				<fuelSystem> Fuel System: Gasoline Direct Injection</fuelSystem>
				<fuelCapacity>Fuel Capacity: 14.8 Gal.</fuelCapacity>
				<gasMileage>Gas Mileage: 30 mpg City / 38 mpg Hwy</gasMileage>
				<fuelType>Fuel Type: Petrol</fuelType>
				<transmission>Transmission: CVT Transmission</transmission>
				<cargoAreaDimensions>Trunk Space (cubic Feet):16.7 </cargoAreaDimensions>
				<steering> Steering Type: Rack-Pinion</steering>
				<frontSuspension> Front Suspension Type: Strut </frontSuspension>
				<rearSuspension> Rear Suspension Type: Multi-link </rearSuspension>
				<brakeType>Brake Type: 4-Wheel Disc</brakeType>
				<antiLockBraking>Anti-Lock-Braking System: 4-Wheel</antiLockBraking>			
				<WheelSize> Wheel Size (inches): 17X7.5 </WheelSize>
				<WheelMaterial>  Wheel Material: Alumnium </WheelMaterial>
				<tireSize>Tire Size: P225/50VR17</tireSize>
				<carPrice>Starting Price: $24,975</carPrice>
				<Review Comfort="4.8" ExteriorStyling="4.9" InteriorDesign="4.8" Performance="4.8" Reliability="4.7" ValueForTheMoney="4.6" >Review: 4.6</Review>
				<quantity>In stock: 5</quantity>
				</specification>
				<accord1/>
		</Car>
		<Car>
			<modelName modelNumber="Au-1563-4590"> A5 Coupe Premium 2.0 TFSI quattro</modelName>
			<audi/>
			<carDescription>
				<h1> Description </h1>
				<p>
					The Accord is Honda’s five-seat mid-size family sedan. Now in its 10th generation, 
					the front-wheel-drive Accord comes with a standard 192-horsepower, turbocharged 
					1.5-liter four-cylinder engine or an available 252-hp, turbocharged 2.0-liter four-cylinder.
					A six-speed manual transmission is available for both engines. The 1.5-liter engine can also
					work with a continuously variable automatic transmission while the 2.0-liter engine can pair
					with a 10-speed automatic. There’s also an efficient Accord Hybrid with a two-motor hybrid 
					powertrain that incorporates a 2.0-liter four-cylinder and gets an EPA-estimated 48 mpg combined. 
				</p>
			</carDescription>
			<specification>
			<specs>Specifications</specs>
			<carBrand>Make: Audi</carBrand>
			<carType>Type: Coupe</carType>
			<EPAClassification>EPA Classification: Subcompact Cars</EPAClassification>
			<seatCapacity>Seat Capacity: 4</seatCapacity>
			<carColor>Color: Black</carColor>
			<dimension>Dimension (L x W x H): 4673 x 1846 x 1371) mm</dimension>
			<driveType>Drive Type: All Wheel Drive</driveType>
			<engineCapacity> Engine Capacity: 1,997 cc </engineCapacity>
			<engineConfiguration>Engine Type: In-Line 4-Cylinder</engineConfiguration>
			<fuelSystem> Fuel System: Gasoline Direct Injection</fuelSystem>
			<fuelCapacity>Fuel Capacity: 15.3 Gal.</fuelCapacity>
			<gasMileage>Gas Mileage: 30 mpg City / 38 mpg Hwy</gasMileage>
			<fuelType>Fuel Type: Diesel</fuelType>
			<transmission>Transmission: 7-Speed Automatic</transmission>
			<cargoAreaDimensions>Trunk Space (cubic Feet):11.6 </cargoAreaDimensions>
			<steering> Steering Type: Rack-Pinion</steering>
			<frontSuspension> Front Suspension Type: Multi-Link </frontSuspension>
			<rearSuspension> Rear Suspension Type: Multi-link </rearSuspension>
			<brakeType>Brake Type: 4-Wheel Disc</brakeType>
			<antiLockBraking>Anti-Lock-Braking System: 4-Wheel</antiLockBraking>			
			<WheelSize> Wheel Size (inches): 18X8.5 </WheelSize>
			<WheelMaterial>  Wheel Material: Alumnium </WheelMaterial>
			<tireSize>Tire Size: P245/40HR18</tireSize>
			<carPrice>Starting Price: $49,900</carPrice>
			<Review Comfort="5.0" ExteriorStyling="5.0" InteriorDesign="5.0" Performance="5.0" Reliability="5.0" ValueForTheMoney="5.0" >Review: 5.0</Review>
			<quantity>In stock: 3</quantity>
			</specification>
			<audi1/>
		</Car>
		<Car>
			<modelName modelNumber="c-16579-9568"> Civic LX Manual Sedan</modelName>
			<civic/>
			<carDescription>
				<h1> Description </h1>
				<p>
					The Accord is Honda’s five-seat mid-size family sedan. Now in its 10th generation, 
					the front-wheel-drive Accord comes with a standard 192-horsepower, turbocharged 
					1.5-liter four-cylinder engine or an available 252-hp, turbocharged 2.0-liter four-cylinder.
					A six-speed manual transmission is available for both engines. The 1.5-liter engine can also
					work with a continuously variable automatic transmission while the 2.0-liter engine can pair
					with a 10-speed automatic. There’s also an efficient Accord Hybrid with a two-motor hybrid 
					powertrain that incorporates a 2.0-liter four-cylinder and gets an EPA-estimated 48 mpg combined. 
				</p>
			</carDescription>
			<specification>
			<specs>Specifications</specs>
			<carBrand>Make: Honda</carBrand>
			<carType>Type: Sedan</carType>
			<EPAClassification>EPA Classification: Compact Cars</EPAClassification>
			<seatCapacity>Seat Capacity: 5</seatCapacity>
			<carColor>Color: Red</carColor>
			<dimension>Dimension (L x W x H): 4,656 x 1,799 x 1,433) mm</dimension>
			<driveType>Drive Type: Front Wheel Drive</driveType>
			<engineCapacity> Engine Capacity: 1,799 cc </engineCapacity>
			<engineConfiguration>Engine Type: Regular Unleaded I-4</engineConfiguration>
			<fuelSystem> Fuel System: Sequential MPI </fuelSystem>
			<fuelCapacity>Fuel Capacity: 12.4 gal</fuelCapacity>
			<gasMileage>Gas Mileage: 30 mpg City / 38 mpg Hwy</gasMileage>
			<fuelType>Fuel Type: Petrol</fuelType>
			<transmission>Transmission: 6-Speed Manual</transmission>
			<cargoAreaDimensions>Trunk Space (cubic Feet):15.1 </cargoAreaDimensions>
			<steering> Steering Type: Rack-Pinion</steering>
			<frontSuspension> Front Suspension Type: Strut </frontSuspension>
			<rearSuspension> Rear Suspension Type: Multi-link </rearSuspension>
			<brakeType>Brake Type: 4-Wheel Disc</brakeType>
			<antiLockBraking>Anti-Lock-Braking System: 4-Wheel</antiLockBraking>			
			<WheelSize> Wheel Size (inches): 16X7 </WheelSize>
			<WheelMaterial>  Wheel Material: Steel </WheelMaterial>
			<tireSize>Tire Size: P215/55HR16</tireSize>
			<carPrice>Starting Price: $69,850</carPrice>
			<Review Comfort="5.0" ExteriorStyling="5.0" InteriorDesign="4.0" Performance="5.0" Reliability="3.0" ValueForTheMoney="4.0" >Review: 4.0</Review>
			<quantity>In stock: 2</quantity>
			</specification>
			<civic1/>
		</Car>
		<Car>
			<modelName modelNumber="AC-3145-6788"> Accent SEL Sedan IVT</modelName>
			<accent/>
			<carDescription>
				<h1> Description </h1>
				<p>
				The 2019 Hyundai Accent is a subcompact sedan that seats up to five people. It’s powered by a 130-horsepower, 1.6-liter four-cylinder engine that pairs with a six-speed manual or six-speed automatic transmission.
				The Accent's 1.6-liter four-cylinder engine makes 120 horsepower and drives the front wheels through either a six-speed manual or continuously variable automatic transmission (CVT). The four-cylinder is new for 2020 ad we've not tested one, but we expect performance similar to last year's model which offered 130 horsepower. It's clear that ride comfort takes priority over deft handling. 
				</p>
			</carDescription>
			<specification>
			<specs>Specifications</specs>
			<carBrand>Make: Hyundai Motor Company</carBrand>
			<carType>Type: Sedan</carType>
			<EPAClassification>EPA Classification: Compact Cars</EPAClassification>
			<seatCapacity>Seat Capacity: 5</seatCapacity>
			<carColor>Color: Black</carColor>
			<dimension>Dimension (L x W x H): 4,656 x 1,799 x 1,433) mm</dimension>
			<driveType>Drive Type: Front Wheel Drive</driveType>
			<engineCapacity> Engine Capacity: 1,799 cc </engineCapacity>
			<engineConfiguration>Engine Type: Regular Unleaded I-4</engineConfiguration>
			<fuelSystem> Fuel System: Port/Direct Injection </fuelSystem>
			<fuelCapacity>Fuel Capacity: 11.9 gal</fuelCapacity>
			<gasMileage>Gas Mileage: 30 mpg City / 38 mpg Hwy</gasMileage>
